FROM postgres:17.5
RUN apt-get update && apt-get install -y cron procps

COPY backup_script.sh /docker-entrypoint-initdb.d/backup_script.sh
COPY start.sh /start.sh
COPY create_mv.sql /usr/local/bin/scripts/create_mv.sql
COPY refresh_views.sh /usr/local/bin/scripts/refresh_views.sh

COPY create_mv_init.sh /usr/local/bin/create_mv_init.sh
RUN chmod +x /usr/local/bin/create_mv_init.sh

COPY .env /.env

RUN chmod +x /start.sh
RUN chmod +x /docker-entrypoint-initdb.d/backup_script.sh
RUN chmod +x /usr/local/bin/scripts/refresh_views.sh

CMD ["/start.sh"]