# Generated by Django 5.2.1 on 2025-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('user_id', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('positive', models.BooleanField(default=False)),
                ('negative', models.BooleanField(default=False)),
                ('positive_count', models.PositiveIntegerField(default=0)),
                ('negative_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('user_id', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('everyday', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
