# Generated by Django 5.2.1 on 2026-01-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FitDataWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fit_date", models.DateField()),
                ("steps", models.PositiveBigIntegerField(default=0)),
                ("distance", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "burned_calories",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                ("user_id", models.UUIDField(editable=False)),
            ],
            options={
                "db_table": "fitdata_week",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HabitSemana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField(editable=False)),
                ("dia", models.DateField()),
                ("total_habits", models.IntegerField()),
                ("habits_positivos", models.IntegerField()),
                ("habits_negativos", models.IntegerField()),
            ],
            options={
                "db_table": "habit_semana",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ToDoSemana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField(editable=False)),
                ("dia", models.DateField()),
                ("total_todos", models.IntegerField()),
                ("todos_concluidos", models.IntegerField()),
            ],
            options={
                "db_table": "todo_semana",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FitData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fit_date", models.DateField()),
                ("steps", models.PositiveBigIntegerField(default=0)),
                ("distance", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "burned_calories",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                ("user_id", models.UUIDField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("user_id", models.UUIDField(editable=False)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("positive", models.BooleanField(default=False)),
                ("negative", models.BooleanField(default=False)),
                ("positive_count", models.PositiveIntegerField(default=0)),
                ("negative_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ToDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("user_id", models.UUIDField(editable=False)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("done", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["done", "-created"],
            },
        ),
    ]
