# Generated by Django 5.2.1 on 2025-06-01 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['done', '-created']},
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='everyday',
        ),
        migrations.AddField(
            model_name='habit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 13, 59, 28, 325187)),
        ),
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 13, 59, 28, 325187)),
        ),
    ]
