# Generated by Django 5.2.1 on 2025-06-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitCore', '0002_alter_habit_options_alter_todo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
