# Generated by Django 5.2.1 on 2025-07-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitCore', '0003_alter_habit_created_alter_todo_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitSemana',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('total_habits', models.IntegerField()),
                ('habits_positivos', models.IntegerField()),
                ('habits_negativos', models.IntegerField()),
            ],
            options={
                'db_table': 'habit_semana',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToDoSemana',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('total_todos', models.IntegerField()),
                ('todos_concluidos', models.IntegerField()),
            ],
            options={
                'db_table': 'todo_semana',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_date', models.DateField()),
                ('steps', models.PositiveBigIntegerField(default=0)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('burned_calories', models.DecimalField(decimal_places=4, max_digits=12)),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
    ]
